---
image: duplicati
version: v1.0.34
name: Duplicati
description: "[Duplicati](https://www.duplicati.com/) works with standard protocols like FTP, SSH, WebDAV as well as popular services like Microsoft OneDrive, Amazon Cloud Drive & S3, Google Drive, box.com, Mega, hubiC and many others."
ext_release: "v2.2.0.1_stable_2025-11-09"
arch:
  - x86_64
  - armv7
